repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, yaml, markdown, html, css, scss]
        exclude: ^(package-lock\.json|.*\.min\.(js|css))$

  # ESLint for TypeScript/JavaScript linting (if you have ESLint configured)
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'if [ -f package.json ] && grep -q "\"eslint\"" package.json; then npm run lint --if-present; else echo "ESLint not configured, skipping"; fi'
        language: system
        types: [file]
        files: \.(ts|js|tsx|jsx)$
        pass_filenames: false

  # Prevent committing to main/master directly
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
