version: "3.8"

services:
  cubel-cloud:
    build:
      context: .
      target: production
    ports:
      - "80:80"
      - "3001:3001"
    volumes:
      # Mount Database config
      - ./config/database.json:/app/config/database.json:ro
      # Mount OIDC configuration (create this file based on the example)
      - ./config/oidc.json:/app/config/oidc.json:ro
      # Mount application registry configuration (create this file based on the example)
      - ./config/applications.json:/app/config/applications.json:ro
      # Mount Gravatar API key (optional - for enhanced avatar support)
      - ./config/gravatar-api-key:/app/config/gravatar-api-key:ro
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost
      - ENABLE_GRAVATAR_LOGGING=false
    restart: unless-stopped

  # Published image
  published:
    image: docker.io/cubel/cubel-cloud:v0.0.2
    platform: linux/amd64
    ports:
      - "80:80"
      - "3001:3001"
    volumes:
      # Mount Database config
      - ./config/database.json:/app/config/database.json:ro
      # Mount OIDC configuration (create this file based on the example)
      - ./config/oidc.json:/app/config/oidc.json:ro
      # Mount application registry configuration (create this file based on the example)
      - ./config/applications.json:/app/config/applications.json:ro
      # Mount Gravatar API key (optional - for enhanced avatar support)
      - ./config/gravatar-api-key:/app/config/gravatar-api-key:ro
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost
      - ENABLE_GRAVATAR_LOGGING=false
    restart: unless-stopped
