version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ..:/app:cached
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
